Fix the crash caused by missing argument keys
Test Plan:
1. Send a broadcast in app -> broadcast
2. It doesn't crash with below error any more:
TypeError: send_broadcast() takes exactly 3 arguments (5 given)